# File: /docker-compose.yml
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: motocosmos_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: motocosmos
      MYSQL_USER: motocosmos_user
      MYSQL_PASSWORD: motocosmos_password
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - motocosmos_network

  api:
    build: .
    container_name: motocosmos_api
    restart: unless-stopped
    ports:
      - "8089:8080"
    environment:
      - DATABASE_URL=motocosmos_user:motocosmos_password@tcp(db:3306)/motocosmos?charset=utf8mb4&parseTime=True&loc=Local
      - JWT_SECRET=your-super-secret-jwt-key
      - MAPBOX_TOKEN=your-mapbox-token
      - PORT=8080
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_USE_SSL=false
      - MINIO_BUCKET_NAME=motocosmos-posts
    depends_on:
      - db
    networks:
      - motocosmos_network
    volumes:
      - ./uploads:/app/uploads

  redis:
    image: redis:7-alpine
    container_name: motocosmos_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - motocosmos_network
  mailhog:
    image: mailhog/mailhog
    container_name: motocosmos_mailhog
    ports:
      - "8025:8025"          # Web UI:    http://localhost:8025
      - "1029:1029"          # SMTP szerver: 1029-Ã¶s porton
    networks:
      - motocosmos_network
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: motocosmos_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"            # Web UI:    http://localhost:8081
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: motocosmos_user
      PMA_PASSWORD: motocosmos_password
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - motocosmos_network
  
  minio:
    image: quay.io/minio/minio:latest
    container_name: motocosmos_minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - motocosmos_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    


volumes:
  mysql_data:
  minio_data:

networks:
  motocosmos_network:
    driver: bridge